version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sns-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2uooy1fygipj"
s3_prefix = "sns-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

